[package]
name = 'helloextendr'
publish = false
version = '0.3.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'helloextendr'

[dependencies]
extendr-api = { git = "https://github.com/Ilia-Kosenkov/extendr/", branch = "prototype/Ellipsis"}
