# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

#' @export
iter_dots <- function(...) invisible(.Call(wrap__iter_dots, environment()))

#' @export
trycatch_dots <- function(...) .Call(wrap__trycatch_dots, environment())

trycatch_dots_result <- function(...) .Call(wrap__trycatch_dots_result, environment())

#' @export
eval_dots <- function(...) .Call(wrap__eval_dots, environment())

#' @export
collect_dots <- function(...) .Call(wrap__collect_dots, environment())

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)


# nolint end
